### ISSUE TITLE
整理前端文档目录

### ISSUE THREAD

**Issue by LuiCat** [BITFierce/smcclass#6]
把次要的页面全部收入子文件夹，主文件夹下只保留用户可以直接访问的页面。js和css尽量不要移动，尽量只修改html里的路径（实在不行就因地制宜）。

**Comment by ricenoddle** [comment]
I'll try my best to do it !

**Comment by ricenoddle** [comment]
现在要进行目录的整理实在是太麻烦了，我觉得就不要移动子页面了
